FROM jenkins/jenkins:lts

USER root

'RUN jenkins-plugin-cli --plugins \
  blueocean \
  build-timestamp \
  timestamper \
  pollscm'

RUN jenkins-plugin-cli --plugins \
  workflow-aggregator \
  git \
  github \
  credentials-binding \
  timestamper \
  build-timestamp \
  pollscm

COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
ENV JENKINS_URL="http://jenkins:8080"

ENV FLUENTD_HOST=fluentd
ENV FLUENTD_PORT=24224

ENV ACCESS_KEY=${ACCESS_KEY}
ENV SECRET_KEY=${SECRET_KEY}

USER jenkins