FROM python:3.10-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    gcc \
    curl \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mlflow boto3

EXPOSE 5000

ENV MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

ENTRYPOINT ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////mnt/mlflow/mlflow.db", "--default-artifact-root", "s3://cd4ml-ml-flow-bucket/"]