FROM jenkins/jenkins:lts

USER root

# 🔥 Instala dependências + Docker CLI
RUN apt-get update && apt-get install -y \
    git \
    curl \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

# 🔥 adiciona Jenkins ao grupo docker (IMPORTANTE)
RUN groupadd -f docker && usermod -aG docker jenkins

# Plugins Jenkins
RUN jenkins-plugin-cli --plugins \
  workflow-aggregator \
  git \
  github \
  credentials-binding \
  timestamper \
  build-timestamp \
  pollscm \
  docker-workflow

# Configuração inicial
COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/

# Jenkins settings
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
ENV JENKINS_URL="http://jenkins:8080"

# Fluentd
ENV FLUENTD_HOST=fluentd
ENV FLUENTD_PORT=24224

# ❌ NÃO recomendado (deixa isso fora depois)
ENV ACCESS_KEY=${ACCESS_KEY}
ENV SECRET_KEY=${SECRET_KEY}

USER jenkins