FROM python:3.10-slim

USER root

ENV FLUENTD_HOST=fluentd
ENV FLUENTD_PORT=24224

ENV FLASK_APP=cd4ml.app
ENV FLASK_ENV=production

ENV MLFLOW_TRACKING_URL=http://mlflow:5000

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY cd4ml ./cd4ml

EXPOSE 5005

CMD ["flask", "run", "--host=0.0.0.0", "--port=5005"]