create-bucket:
  image: minio/mc
  depends_on:
    minio:
      condition: service_healthy
  entrypoint: >
    /bin/sh -c "
    mc alias set myminio http://minio:9000 $ACCESS_KEY $SECRET_KEY;
    mc mb myminio/cd4ml-ml-flow-bucket;
    exit 0;
    "
  networks:
    - jenkins_nw